seed: 25
spanning: 2.5 # 2.5 years of data for modelling
frequency: "h" # The data granularity for model development; hour.
seasons:
  number_of: 12 # 12 months
  steps_per: [744, 672, 744, 720, 720, 744, 744, 744, 720, 744, 720, 744] # The hours per month, start from January.
testing: 96 # hours - The testing stage will span these number of hours of
ahead: 264 # hours - The number of prediction hours ahead
n_variational_steps: 200 # Refer to num_steps within https://www.tensorflow.org/probability/api_docs/python/tfp/vi/fit_surrogate_posterior
learning_rate: 0.1 # For optimisation algorithms
n_samples: 35 # For requesting samples from (a) structural time series forecasts, and (b) structural time series one-step-predictive predictions
s3:
  p_bucket: "internal" # An Amazon S3 (Simple Storage Service) bucket parameter; vis-à-vis source.  The corresponding argument is an Amazon S3 bucket value.
  p_prefix: "path_internal_data" # The Amazon S3 prefix parameter; vis-à-vis source.  The corresponding argument is an Amazon S3 prefix value.
  affix: "resamples" # Extends the prefix; vis-à-vis source.
series:
  excerpt: [56884010, 57031010, 57240010, 57491010, 57976010, 58179010, 59752010, 51453010, 55408010, 55440010, 55351010, 55367010, 55481010, 55513010, 55157010, 55538010, 55221010, 55237010, 55205010, 55285010, 55465010, 55173010, 55189010, 55326010, 55383010, 55554010, 55253010, 55424010, 55301010, 55269010, 55497010, 58868010, 60116010, 61541010, 61525010] # If null, models are built for all series/gauges
cpu: True # Should computations proceed via a machine's Central Processing Unit only?  If False, computation will proceed via both graphics processing unit and central processing unit.